local dap = require("dap")
vim.fn.sign_define('DapBreakpoint', { text = '🔴', texthl = '', linehl = '', numhl = '' })
vim.fn.sign_define('DapBreakpointCondition', { text = '⚠️', texthl = '', linehl = '', numhl = '' })
vim.fn.sign_define('DapLogPoint', { text = '🔍', texthl = '', linehl = '', numhl = '' })
vim.keymap.set("n", "<F8>", dap.continue, { noremap = true, silent = true })
vim.keymap.set("n", "<F9>", dap.step_over, { noremap = true, silent = true })
vim.keymap.set("n", "<F7>", dap.step_into, { noremap = true, silent = true })
vim.keymap.set("n", "<F12>", dap.step_out, { noremap = true, silent = true })
vim.keymap.set("n", "<leader>tb", dap.toggle_breakpoint, { noremap = true, silent = true })
vim.keymap.set('n', '<Leader>lp', dap.list_breakpoints, { noremap = true, silent = true })

